name: Build and Push Aether Image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 1'

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: aether
      REGISTRY: ghcr.io
      IMAGE_OWNER: phonowon
      UNIQUE_TAG: ${{ github.run_number }}-${{ github.sha }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Just
        run: |
          sudo apt-get update
          sudo apt-get install -y just


      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: |
          echo "Building $IMAGE_NAME:$UNIQUE_TAG"
          just build $IMAGE_NAME $UNIQUE_TAG

      - name: Tag image for GHCR
        run: |
          podman tag $IMAGE_NAME:$UNIQUE_TAG $REGISTRY/$IMAGE_OWNER/$IMAGE_NAME:$UNIQUE_TAG

      - name: Push image
        run: |
          podman push $REGISTRY/$IMAGE_OWNER/$IMAGE_NAME:$UNIQUE_TAG

      - name: Update stable tag
        if: github.ref == 'refs/heads/main'
        run: |
          podman tag $REGISTRY/$IMAGE_OWNER/$IMAGE_NAME:$UNIQUE_TAG $REGISTRY/$IMAGE_OWNER/$IMAGE_NAME:stable
          podman push $REGISTRY/$IMAGE_OWNER/$IMAGE_NAME:stable
